import {
  Box,
  Button,
  Checkbox,
  Container,
  Flex,
  Heading,
  HStack,
  Input,
  Radio,
  RadioGroup,
  Stack,
  useToast,
  VStack,
} from "@chakra-ui/react";
import Head from "next/head";
import { useMemo, useState } from "react";

interface Game {
  id: number;
  name: string;
  size: number;
}

function formatBytes(bytes: number, decimals = 2) {
  if (!+bytes) return "0 Bytes";

  const k = 1024;
  const dm = decimals < 0 ? 0 : decimals;
  const sizes = ["Bytes", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"];

  const i = Math.floor(Math.log(bytes) / Math.log(k));

  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(dm))} ${sizes[i]}`;
}

interface HomeProps {
  games: Game[];
}

export default function Home({ games: gamesContent }: HomeProps) {
  const [pendriverSize, setPendriverSize] = useState("4e+9");
  const toast = useToast();

  const [gamesSelecteds, setGamesSelecteds] = useState<Game[]>([]);
  const [searchGame, setSearchGame] = useState("");
  const [name, setName] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const games: Game[] = useMemo(() => {
    return gamesContent.filter(
      (game) =>
        !gamesSelecteds.some((gameSelected) => gameSelected.id === game.id) &&
        (searchGame.length === 0 ||
          game.name.toLowerCase().includes(searchGame.toLowerCase()))
    );
  }, [gamesSelecteds, searchGame, gamesContent]);

  const sizeTotalOfGamesSelecteds = useMemo(() => {
    return gamesSelecteds.reduce((total, game) => total + game.size, 0);
  }, [gamesSelecteds]);

  const handleSendMessage = async () => {
    setIsLoading(true);

    const gamesText = gamesSelecteds
      .map((game) => `${game.name} - ${formatBytes(game.size)}`)
      .join("\n");

    const text = `CLIENTE\n\n${name}\n\nPendriver ${formatBytes(
      Number(pendriverSize)
    )}\n\nJOGOS - ${formatBytes(sizeTotalOfGamesSelecteds)}\n\n${gamesText}`;

    fetch(
      encodeURI(
        `https://api.telegram.org/bot${process.env.NEXT_PUBLIC_BOT_TOKEN}/sendMessage?chat_id=${process.env.NEXT_PUBLIC_CHAT_ID}&text=${text}`
      ),
      {
        method: "POST",
      }
    )
      .then((data) => {
        if (data.status >= 400) {
          toast({
            description: "Falha ao fazer o pedido. Tente novamente em breve",
            status: "error",
            position: "top-right",
            duration: 5000,
          });
        } else {
          toast({
            description: "Pedido feito com sucesso!!",
            status: "success",
            position: "top-right",
            duration: 5000,
          });
          setName("");
          setSearchGame("");
          setGamesSelecteds([]);
        }
      })
      .catch(() =>
        toast({
          description: "Falha ao fazer o pedido. Tente novamente em breve",
          status: "error",
          position: "top-right",
          duration: 5000,
        })
      )
      .finally(() => {
        setIsLoading(false);
      });
  };

  return (
    <>
      <Head>
        <title>Cyber do Gilberto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="100ch">
        <Heading mt={4} color="primary.500" textAlign="left">
          Qual o tamanho do seu Pendriver?
        </Heading>
        <RadioGroup
          mt={4}
          onChange={(e) => {
            setPendriverSize(e);
            setGamesSelecteds([]);
          }}
          value={pendriverSize}
        >
          <Stack spacing={5} direction="row">
            <Radio colorScheme="primary.500" value="4294967296">
              4GB
            </Radio>
            <Radio colorScheme="primary.500" value="8589934592">
              8GB
            </Radio>
            <Radio colorScheme="primary.500" value="17179869184">
              16GB
            </Radio>
            <Radio colorScheme="primary.500" value="34359738368">
              32GB
            </Radio>
          </Stack>
        </RadioGroup>
        {gamesSelecteds.length > 0 ? (
          // <Box position="sticky" top="0" bg="background" zIndex={10}>
          <Box>
            <Heading mt={4} color="primary.500" textAlign="left">
              Jogos Selecionados
            </Heading>
            <Heading fontSize="xl" mt={4} color="primary.500" textAlign="left">
              Tamanho total - {formatBytes(sizeTotalOfGamesSelecteds)}
            </Heading>
            <VStack alignItems="flex-start" gap={2} mt={6}>
              {gamesSelecteds.map((game) => (
                <Checkbox
                  key={game.id}
                  isChecked={true}
                  onChange={(_) =>
                    setGamesSelecteds((prev) =>
                      prev.filter((gameSelected) => gameSelected.id !== game.id)
                    )
                  }
                >
                  {game.name} - {formatBytes(game.size)}
                </Checkbox>
              ))}
            </VStack>
          </Box>
        ) : null}
        <Heading mt={4} color="primary.500" textAlign="left">
          Escolha os jogos
        </Heading>
        <Input
          value={searchGame}
          onChange={(e) => setSearchGame(e.target.value)}
          placeholder="Pesquisar jogo"
          mt={6}
        />
        <VStack alignItems="flex-start" gap={2} mt={6}>
          {games.map((game) => (
            <Checkbox
              key={game.id}
              isChecked={gamesSelecteds.some(
                (gameSelected) => gameSelected.id === game.id
              )}
              onChange={(_) => {
                const sizeAfterAdd = sizeTotalOfGamesSelecteds + game.size;
                if (sizeAfterAdd > Number(pendriverSize)) {
                  toast({
                    description:
                      "Sem espaço disponível para adicionar mais jogos.",
                    status: "warning",
                    position: "top-right",
                    duration: 5000,
                  });
                } else {
                  setGamesSelecteds((prev) => [...prev, game]);
                }
              }}
            >
              {game.name} - {formatBytes(game.size)}
            </Checkbox>
          ))}
        </VStack>
      </Container>
      <Flex
        zIndex={99999}
        width="100%"
        as="footer"
        position="fixed"
        bottom={0}
        p={6}
        align="center"
        justify="center"
        bg="background"
        direction="column"
        borderTop="solid 1px white"
      >
        <HStack>
          <Input
            flex={1}
            h={50}
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Nome"
          />
          <Button
            h={50}
            px={2}
            isLoading={isLoading}
            onClick={() => {
              if (!name) {
                return toast({
                  description: "Informe seu nome.",
                  status: "warning",
                  position: "top-right",
                  duration: 2000,
                });
              } else if (!gamesSelecteds.length) {
                return toast({
                  description: "Seleciona pelo menos um jogo.",
                  status: "warning",
                  position: "top-right",
                  duration: 2000,
                });
              } else {
                handleSendMessage();
              }
            }}
          >
            Enviar pedido
          </Button>
        </HStack>
      </Flex>
    </>
  );
}

export async function getStaticProps() {
  const params = new URLSearchParams();
  params.append("key", "AIzaSyBmxrl4QRkdtmoiVJjbLd5jU56-Oz-Sw1Q");

  let games: Game[] = [];

  await fetch(
    `https://sheets.googleapis.com/v4/spreadsheets/1KkRyDnxzc5NwaQ00gODBJJ1MPz7hof1whrHYWOYHa-s/values/JOGOS PS2/?${params.toString()}`
  ).then((data) => {
    return data.json().then((data) => {
      console.log(data);
      games =
        data?.values?.map((row: string[], id: number) => ({
          id,
          name: row[0] ?? "",
          size: Number(row[1] ?? 0),
        })) ?? [];
    });
  });

  return {
    props: {
      games,
    },
  };
}
